version: "3.7"

services:
  api:
    image: felipecwb/omnistack11-api
    build: .
    command: npm run development
    environment:
      NODE_ENV: 'development'
    ports:
      - 3000:3000
    volumes:
      - ./:/home/api
      - ./database:/home/api/database
